### PR TITLE
Added example file containing example script of how to get web/net sc…

### PR DESCRIPTION
**Pull request by olobjo**
…ans as JSON data in a list. Test stubs created.

To test code:
1. pull repo
2. run code from terminal / CLI as such: `$ python3 api-examples.py` 
3. To see available parameters, please run: `$ python3 api-examples.py -h`

### CODE REVIEW

**Review by Septimus7 — COMMENTED** [review]
Looks really good!

A few remarks that I have:
- Functions like `get_api_data` could look better in a separate file, as they are helpers
- I'm not sure if I like adding tests which don't do anything
- I'd think about adding some expected results of the functions at the end

**Comment by olobjo** [comment]
> Looks really good!
> 
> A few remarks that I have:
> 
> * Functions like `get_api_data` could look better in a separate file, as they are helpers
> * I'm not sure if I like adding tests which don't do anything
> * I'd think about adding some expected results of the functions at the end

Thank you Tomaz!
Please see revisions after review

**Comment by Skruvkork** [comment]
As far as I can tell it looks good, and you seem to have fixed the things that were pointed out earlier.
I'd say you can go ahead and merge this 👍

**Review by Septimus7 — APPROVED** [review]
Yes, now after those changes everything looks really good to me 👍

**Pull request merged**
